### ISSUE TITLE
build failure on macOS, FreeBSD: <endian.h> not found

### ISSUE THREAD

**Issue by adaugherity** [ipmitool/ipmitool#101]
```
/bin/sh ../libtool --silent  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I/usr/local/opt/openssl/include  -g -O2 -Wall -Wextra -std=gnu11 -pedantic -Wformat -Wformat-nonliteral -c -o ipmi_mc.lo ipmi_mc.c
ipmi_mc.c:39:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
```
git blame says this was added in 6c00d448, so it was not broken in any releases... this is easily fixed by changing it to `#include <machine/endian.h>`, which is where these OSes install that header.

I don't know the best portable way to fix this... maybe some AC_CHECK_HEADER stuff to first try `<endian.h>`, then `<machine/endian.h>` if that doesn't work?

**Comment by AlexanderAmelkin** [comment]
Looks like that `#include` is a left-over I forgot to remove. That commit introduces `ipmi16toh()` and later commits add more of its kin exactly to overcome the need to include `endian.h` which does not exist for Windows and MacOS. For the latter it can be added indeed as `machine/endian.h`, but I decided there that I'd better define local versions of those simple routines. Apparently, I forgot to remove the reference to `endian.h`. It is not needed.
