### ISSUE TITLE
Clean up use of strcmp/strncmp/strncasecmp for command line arguments

### ISSUE THREAD

**Issue by AlexanderAmelkin** [ipmitool/ipmitool#104]
This is associated with [SourceForge ticket 24](https://sourceforge.net/p/ipmitool/bugs/24/).
In many places command line arguments are matched using some weird constructions like
```
if (strncmp(argv[i], "option", strlen("option")) == 0)
```
or
```
if (strncmp(argv[i], "option", 7) == 0)
```
or
```
if (strncmp(argv[i], "option", 7) == 0 && strncmp(argv[i], "option", strlen(argv[i])) == 0)
```
or even
```
if (! (strncmp(argv[i], "option", __maxlen(7, strlen(argv[i])) == 0) )
```
In some places even `strncasecmp()` is used.

All those approaches look awfully redundant, cumbersome and unprofessional. They also lead to problems described in aforementioned ticket.

This issue is to capture the effort to clean them all up and switch to using simple `strcmp()` wherever normal C strings coming from command line arguments or console input are compared.

There are also places where `strncmp()` is used to compare IPMI strings without the null-byte terminator and with a type/length byte prefix instead. Those must be left as is (or maybe converted to using some new helper function like `ipmi_strcmp()`).

**Comment by doublechiang** [comment]
anything I can do for this ticket?
