### ISSUE TITLE
Error occurred when using coroutine to run ipmitool Static library

### ISSUE THREAD

**Issue by leye7755** [ipmitool/ipmitool#112]
when we call ipmi_main as library twice in one coroutine.  
Error info:
Error in open session response message : insufficient resources for role

**Comment by AlexanderAmelkin** [comment]
ipmitool is not designed for use as a library, most of its functions are not reentrant and are not thread-safe. It has never been announced that such a use is possible, so I'm closing this issue as not a bug.
