### ISSUE TITLE
encounter Segmentation fault  when using ipmitool

### ISSUE THREAD

**Issue by leye7755** [ipmitool/ipmitool#118]
Core was generated by` ipmitool -I lanplus -H xxxxxx -U xxxx -P XXXXXXXXX raw 0x3a 0x71 0x01`
Program terminated with signal 11, Segmentation fault.

Why does this problem arise?  We use popen to use ipmitool

**Comment by leye7755** [comment]
@AlexanderAmelkin

**Comment by leye7755** [comment]
Looking forward to and thanking you for your help。@AlexanderAmelkin

**Comment by leye7755** [comment]
using sdr module  encountered a problem:
debug details:
ipmi_sdr.c : ipmi_ipmi_sdr_read_sensor_value() call ipmi_sdr_get_unit_string( intf, pct, type, base,modifier)
and  base is 255 which exceed the size of unit_desc array  .   leading to Segmentation fault。

**Comment by AlexanderAmelkin** [comment]
Can you please run `ipmitool` with nine `-v` arguments (that is, `ipmitool -vvvvvvvvv ...`) and attach (don't copy-paste) the output here? It's unclear why `base` is 255. Looks like an invalid response from your BMC. I'd like to see the full communication log to understand how to properly handle it.

**Comment by leye7755** [comment]
@AlexanderAmelkin Can i send # your email? can't find the way to attach log.

**Comment by AlexanderAmelkin** [comment]
Please check the branch from PR #120

**Comment by AlexanderAmelkin** [comment]
As for attachments, there is the "Attach files by dragging..." string right below the comment entry box here on this page.

**Comment by AlexanderAmelkin** [comment]
Sorry, committed the wrong version there. Will fix soon.

**Comment by leye7755** [comment]
[sdr.log](https://github.com/ipmitool/ipmitool/files/3101861/sdr.log)
this is sdr log

**Comment by AlexanderAmelkin** [comment]
@leye7755, I don't see a segmentation fault in the attached log. Is it the log from #120 ?

**Comment by leye7755** [comment]
[sdr-20190423.log](https://github.com/ipmitool/ipmitool/files/3105483/sdr-20190423.log)
I add comment  in ipmi_sdr.c : ipmi_sdr_get_unit_string() 
printf("#test:%d#\n",base);

**Comment by AlexanderAmelkin** [comment]
I now see it hit the wrong string for `CPU1 DTS` sensor.
That's quite expected with the old code, there is no range check in it.
Have you tried running the code from #120 ?

**Comment by AlexanderAmelkin** [comment]
It's unclear though why `base` is 0xFF, or to be more precise, why only 19 bytes of SDR Record are requested by `ipmitool` (see line 2379 of your sdr-20190423.log) when unit info is in bytes 21-23.
I'll look into it further, but I suspect there may be some invalid response from your BMC involved.

**Comment by AlexanderAmelkin** [comment]
Ok, those 19 bytes are just a remainder of total 51 bytes minus 32 bytes read earlier. Digging further...

**Comment by AlexanderAmelkin** [comment]
@leye7755, please tell how the program behaves if built from PR #120.
