### ISSUE TITLE
Can't get response on ipmitool side

### ISSUE THREAD

**Issue by matthewcunningham** [ipmitool/ipmitool#123]
I'm able to confirm ipmitool is sending valid requests to my device and that my device is responding to those requests. However, ipmitool is not seeing the responses.

**ipmiTool output:**
`user@ubuntu:~$ ipmitool -v -v  -I serial-basic -D /dev/ttyUSB0:57600 raw 06 01
Running Get PICMG Properties my_addr 0x20, transit 0, target 0
No response from Get PICMG Properties
Running Get VSO Capabilities my_addr 0x20, transit 0, target 0
No valid response received
Acquire IPMB address
Discovered IPMB address 0x0
Interface address: my_addr 0x20 transit 0:0 target 0x20:0 ipmb_target 0

RAW REQ (channel=0x0 netfn=0x6 lun=0x0 cmd=0x1 data_len=0)
Unable to send RAW command (channel=0x0 netfn=0x6 lun=0x0 cmd=0x1)
` 

**Device serial console output:**
`>SER  : 00005000 : received : 20B030810400007B
To: ChM:0   Fr: 20:0     - NetFn: b0 Cmnd: 0 - request

>SER  : 00005000 : send     : 81B4CB200400C11B
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - error c1

>SER  : 00005000 : received : 20B0308108000077
To: ChM:0   Fr: 20:0     - NetFn: b0 Cmnd: 0 - request

>SER  : 00005000 : send     : 81B4CB200800C117
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - error c1

>SER  : 00005000 : received : 20B030810C000073
To: ChM:0   Fr: 20:0     - NetFn: b0 Cmnd: 0 - request

>SER  : 00005000 : send     : 81B4CB200C00C113
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - error c1

>SER  : 00005000 : received : 20B030811000006F
To: ChM:0   Fr: 20:0     - NetFn: b0 Cmnd: 0 - request

>SER  : 00005000 : send     : 81B4CB201000C10F
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - error c1

>SER  : 00005000 : received : 20B030811400006B
To: ChM:0   Fr: 20:0     - NetFn: b0 Cmnd: 0 - request

>SER  : 00005000 : send     : 81B4CB201400C10B
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - error c1

>SER  : 00005000 : received : 20B0308118000364
To: ChM:0   Fr: 20:0     - Get VSO Capability - request

>SER  : 00005000 : send     : 81B4CB2018000003011100010000B2
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - response

>SER  : 00005000 : received : 20B030811C000360
To: ChM:0   Fr: 20:0     - Get VSO Capability - request

>SER  : 00005000 : send     : 81B4CB201C000003011100010000AE
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - response

>SER  : 00005000 : received : 20B030812000035C
To: ChM:0   Fr: 20:0     - Get VSO Capability - request

>SER  : 00005000 : send     : 81B4CB2020000003011100010000AA
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - response

>SER  : 00005000 : received : 20B0308124000358
To: ChM:0   Fr: 20:0     - Get VSO Capability - request

>SER  : 00005000 : send     : 81B4CB2024000003011100010000A6
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - response

>SER  : 00005000 : received : 20B0308128000354
To: ChM:0   Fr: 20:0     - Get VSO Capability - request

>SER  : 00005000 : send     : 81B4CB2028000003011100010000A2
To: 20:0     Fr: ChM:0   - NetFn: b0 Cmnd: 0 - response

>SER  : 00005000 : received : 2018C8812C0152
To: ChM:0   Fr: 20:0     - Get Device ID - request

>SER  : 00005000 : send     : 811C63202C01005A830094023F61CE00000000FF0009CA
To: 20:0     Fr: ChM:0   - Get Device ID - response

>SER  : 00005000 : received : 2018C88130014E
To: ChM:0   Fr: 20:0     - Get Device ID - request

>SER  : 00005000 : send     : 811C63203001005A830094023F61CE00000000FF0009C6
To: 20:0     Fr: ChM:0   - Get Device ID - response

>SER  : 00005000 : received : 2018C88134014A
To: ChM:0   Fr: 20:0     - Get Device ID - request

>SER  : 00005000 : send     : 811C63203401005A830094023F61CE00000000FF0009C2
To: 20:0     Fr: ChM:0   - Get Device ID - response

>SER  : 00005000 : received : 2018C881380146
To: ChM:0   Fr: 20:0     - Get Device ID - request

>SER  : 00005000 : send     : 811C63203801005A830094023F61CE00000000FF0009BE
To: 20:0     Fr: ChM:0   - Get Device ID - response

>SER  : 00005000 : received : 2018C8813C0142
To: ChM:0   Fr: 20:0     - Get Device ID - request

>SER  : 00005000 : send     : 811C63203C01005A830094023F61CE00000000FF0009BA
To: 20:0     Fr: ChM:0   - Get Device ID - response`

Is there any way to get ipmitool to print out what it receives if it chooses to reject/drop the packet?

**Comment by AlexanderAmelkin** [comment]
@matthewcunningham, I see you've closed the ticket. Was the problem resolved for you? Please log here what was causing the problem. That information may serve other users.
