### ISSUE TITLE
Power consumption with user privilege

### ISSUE THREAD

**Issue by nodorgrom** [ipmitool/ipmitool#188]
Good morning, I have x10 supermicro bare metal server with ipmi, also I'm need to collection sensor's data and power consumption with zabbix ipmi interface.
At the moment I can collect just sensor's data but I can't receive consumption data (dcmi power reading) because user has "USER" privilege. If I'll grant next level of privilege (it's OPERATOR) then user will be able rebooting via dcmi power reset.
I suggest to allow get only power consumption via dcmi power reading with "user" privilege

**Comment by AlexanderAmelkin** [comment]
Your request has nothing to do with `ipmitool`. Access rights are managed and enforced on the BMC side.
