### ISSUE TITLE
Build ipmitool-1.8.18 cygwin windows error messages "output from gcc object... failed"

### ISSUE THREAD

**Issue by JohnCenteno** [ipmitool/ipmitool#200]
Dear All,

Why I got below message when I run ./configure under Cygwin Windows? Thanks.

checking command to parse /usr/bin/nm -B output from gcc object... failed

ipmitool 1.8.18
Interfaces
  lan     : yes
  lanplus : yes
  open    : no
  free    : no
  imb     : no
  bmc     : no
  usb     : no
  lipmi   : no
  serial  : yes
  dummy   : no

Extra tools
  ipmievd   : yes
  ipmishell : no

**Comment by AlexanderAmelkin** [comment]
Please refer to the instructions given in `INSTALL` file on how to build for Windows.
Those instructions are verified by GitHub Workflows and thus are known to be correct.
