### ISSUE TITLE
Build ipmitool-1.8.18 cygwin windows error messages "libtool:   error: object name conflicts in archive:"

### ISSUE THREAD

**Issue by JohnCenteno** [ipmitool/ipmitool#201]
Dear All,

Why I got bellows message when I run make when I build ipmitool-1.8.18 cygwin windows? Thanks.
mv -f .deps/lan.Tpo .deps/lan.Plo
/bin/sh ../../../libtool --silent  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../..  -I../../../include   -g -O2 -Wall -Wextra -std=gnu99 -pedantic -Wformat -Wformat-nonliteral -MT auth
.lo -MD -MP -MF .deps/auth.Tpo -c -o auth.lo auth.c
mv -f .deps/auth.Tpo .deps/auth.Plo
/bin/sh ../../../libtool --silent  --tag=CC   --mode=link gcc  -g -O2 -Wall -Wextra -std=gnu99 -pedantic -Wformat -Wformat-nonliteral   -o libintf_lan.la  lan.lo auth.lo md5.lo ../../../lib/libipmi
tool.la -lcrypto
mv -f .deps/lan.Tpo .deps/lan.Plo
/bin/sh ../../../libtool --silent  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../..  -I../../../include   -g -O2 -Wall -Wextra -std=gnu99 -pedantic -Wformat -Wformat-nonliteral -MT auth
.lo -MD -MP -MF .deps/auth.Tpo -c -o auth.lo auth.c
mv -f .deps/auth.Tpo .deps/auth.Plo
/bin/sh ../../../libtool --silent  --tag=CC   --mode=link gcc  -g -O2 -Wall -Wextra -std=gnu99 -pedantic -Wformat -Wformat-nonliteral   -o libintf_lan.la  lan.lo auth.lo md5.lo ../../../lib/libipmi
tool.la -lcrypto
libtool:   error: object name conflicts in archive: .libs/libintf_lan.lax/libipmitool.a//cygdrive/c/ipmitool-1.8.18/src/plugins/lan/../../../lib/.libs/libipmitool.a
make[4]: *** [Makefile:395: libintf_lan.la] Error 1
make[4]: Leaving directory '/cygdrive/c/ipmitool-1.8.18/src/plugins/lan'
make[3]: *** [Makefile:485: all-recursive] Error 1
make[3]: Leaving directory '/cygdrive/c/ipmitool-1.8.18/src/plugins'
make[2]: *** [Makefile:584: all-recursive] Error 1
make[2]: Leaving directory '/cygdrive/c/ipmitool-1.8.18/src'
make[1]: *** [Makefile:459: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/ipmitool-1.8.18'
make: *** [Makefile:390: all] Error 2

Administrator@WIN-1TKMIK221C4 /cygdrive/c/ipmitool-1.8.18
.libs/libintf_lan.lax/libipmitool.a//cygdrive/c/ipmitool-1.8.18/src/plugins/lan/../../../lib/.libs/libipmitool.a
make[4]: *** [Makefile:395: libintf_lan.la] Error 1
make[4]: Leaving directory '/cygdrive/c/ipmitool-1.8.18/src/plugins/lan'
make[3]: *** [Makefile:485: all-recursive] Error 1
make[3]: Leaving directory '/cygdrive/c/ipmitool-1.8.18/src/plugins'
make[2]: *** [Makefile:584: all-recursive] Error 1
make[2]: Leaving directory '/cygdrive/c/ipmitool-1.8.18/src'
make[1]: *** [Makefile:459: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/ipmitool-1.8.18'
make: *** [Makefile:390: all] Error 2

Administrator@WIN-1TKMIK221C4 /cygdrive/c/ipmitool-1.8.18

**Comment by AlexanderAmelkin** [comment]
Please refer to the instructions given in `INSTALL` file on how to build for Windows.
Those instructions are verified by GitHub Workflows and thus are known to be correct.
