### ISSUE TITLE
Assertion:Undefined MRC code (FE 4C 00 40) log on Cascade Lake CPU like gold 6248 CPU

### ISSUE THREAD

**Issue by JohnCenteno** [ipmitool/ipmitool#204]
Dear All,

Does IPMITOOL V1.8.18 support Casecade Lake CPU like Intel gold 6248 CPU? My system has event log like below? Thanks a lot.

2 | 2020/05/12 17:58:38 | BIOS OEM 
    | Assertion:Undefined MRC code (FE 4C 00 40)

**Comment by doublechiang** [comment]
This is nothing related to ipmitool, ask your server manufacturer on the definition on that SEL log.

**Comment by JohnCenteno** [comment]
Dear Sirs,

Thanks.
