### ISSUE TITLE
Plugin for remote gdb over ipmitool SOL

### ISSUE THREAD

**Issue by vaslot** [ipmitool/ipmitool#211]
This is a wish and figured I put it out there in case anyone's thought about it already. I've been wanting to use ipmi SOL connection to debug a remote Linux system using gdb. gdb can connect to the remote system over serial or network. Perhaps the changes needs to be in gdb. See "(gdb) target remote ..." command.

**Comment by AlexanderAmelkin** [comment]
The changes need to be in gdbserver so that it could connect over stdin/stdout, not just serial.
Please ask for this in gdb community. ipmitool sol is strictly following the IPMI specification and has nothing to do with any of the remote host applications, one of which is the gdb is.
