### ISSUE TITLE
Replace curl argument

### ISSUE THREAD

**Issue by Ypnose** [ipmitool/ipmitool#218]
Hey,
When attempting to download IANA PEN database with `curl`, it might fail with this error message :
```
Downloading IANA PEN database...
curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
FAILED to download the IANA PEN database
```
It is probably related to `-#` argument in `curl` command, which is launched without escaping. Would you agree to replace it by `--progress-bar` ? It's the human friendly counterpart option. I can submit a pull request if you like.

**Comment by AlexanderAmelkin** [comment]
@Ypnose Seems reasonable, please submit a PR

**Comment by Ypnose** [comment]
Please wait before applying pull request, I just noticed the link has changed. `curl` command needs to be updated with `-L` too.
```
$ curl -LI http://www.iana.org/assignments/enterprise-numbers
HTTP/1.1 301 Moved Permanently
Date: Tue, 21 Jul 2020 05:30:35 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Referrer-Policy: origin-when-cross-origin
Content-Security-Policy: upgrade-insecure-requests
Location: https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers
Cache-Control: public, s-maxage=1800, max-age=3600
Expires: Tue, 21 Jul 2020 06:30:35 GMT
Content-Type: text/html; charset=iso-8859-1
```

**Comment by AlexanderAmelkin** [comment]
Sure, do it in the same PR please.

**Comment by AlexanderAmelkin** [comment]
Also, to block a PR, you may just add "WIP" to it's title. That will fail the WIP plugin check and prevent merging.

**Comment by Ypnose** [comment]
Thanks for the insight. I submitted this change in the same PR. As the checks are all good, I took the initiative to remove "WIP" from the title. It sounds all good.
