### ISSUE TITLE
Boot device options regression bug

### ISSUE THREAD

**Issue by ezanolin** [ipmitool/ipmitool#223]
I was looking to solve my "options=persistent,efiboot" problem in issue [163](https://github.com/ipmitool/ipmitool/issues/163) that was resolved as part of issue [165](https://github.com/ipmitool/ipmitool/issues/165) and the latest master was worse. The debug output seems to indicate that no options are being parsed at all (not just overwriting each other).

I have tried commit directly after the 165 fix [4b89f1b42d94a9bb96093d5e5237c7f1cfd84580](https://github.com/ipmitool/ipmitool/commit/4b89f1b42d94a9bb96093d5e5237c7f1cfd84580) and that one works great.

Let me know if you want me to perform any testing.
Thank you.

**Comment by AlexanderAmelkin** [comment]
Yes, indeed there is a regression introduced by 6e037d6bfbbb93b349c8ca331ebde03a837f76bf.
Please check the bugfix branch.
