### ISSUE TITLE
sometime ipmi_si can't detect BMC

### ISSUE THREAD

**Issue by yangxuan8282** [ipmitool/ipmitool#227]
ipmi_si modules on our server not working proper after performing several reboots.

the kernel log look this:

```
kernel: [   24.422640] KCS: State = 5, 44
kernel: [   24.434358] KCS: State = 5, 44
kernel: [   24.446078] KCS: State = 5, 45
kernel: [   24.446084] KCS: State = 5, 46
kernel: [   24.453890] KCS: State = 5, 45
kernel: [   24.453895] KCS: State = 5, 46
kernel: [   24.465608] KCS: State = 5, 45
kernel: [   24.465613] KCS: State = 5, 46
kernel: [   24.477325] KCS: State = 5, 5
kernel: [   24.477336] ipmi_si hardcode-ipmi-si.0: There appears to be no BMC at this location
```

according to ipmi_kcs_sm.c in kernel, the `KCS: State =5, ` seems stand 
for  `KCS_WAIT_READ`, but I don't know the meaning of 44,45,46 and 5

and I can still read info use ipmitool from other machine

**Comment by AlexanderAmelkin** [comment]
@yangxuan8282 ipmitool project has nothing to do with ipmi_si kernel module aside from using it. Please report the bug to the appropriate kernel mail list.
