### ISSUE TITLE
command sol activate no output

### ISSUE THREAD

**Issue by etiaxie** [ipmitool/ipmitool#24]
ipmitool version:1.8.18
I am fresh for ipmitool and i just try to connect tarfet terminal but get nothing after "sol activate"
ipmitool -H 10.192.83.205 -I lanplus -U ADMIN -P hik12345+ sol info 1
Set in progress                 : set-complete
Enabled                         : true
Force Encryption                : false
Force Authentication            : false
Privilege Level                 : OPERATOR
Character Accumulate Level (ms) : 0
Character Send Threshold        : 0
Retry Count                     : 0
Retry Interval (ms)             : 0
Volatile Bit Rate (kbps)        : 115.2
Non-Volatile Bit Rate (kbps)    : 115.2
Payload Channel                 : 1 (0x01)
Payload Port                    : 623

>ipmitool -H 10.192.83.205 -I lanplus -U ADMIN -P hik12345+ sol activate
[SOL Session operational.  Use ~? for help]
======here no other output

**Comment by AlexanderAmelkin** [comment]
That's normal. This means that you have successfully connected to a remote BMC and activated a SOL session, but there is just no ouput from your host on the serial port. Have you turned on your host? Is it configured to output anything on the serial port connected to BMC?

Please contact the vendor of your server for further assistance.
