### ISSUE TITLE
FW upgrades using IPMI for HP ILO3 gen7

### ISSUE THREAD

**Issue by shaikk-arch** [ipmitool/ipmitool#253]
Hi @AlexanderAmelkin 

How are you ?
I am not sure if i can ask here or not 

Could you able to tell me if there is a way i can update ILO Firmware using IPMI tool ? i was looking into all doc but no luck ?  please help me with the command it would be helpful 
I have all ILO3 Gen7 1.87 version which needs an upgrade, i tried using "hpilo and RestAPI" on ubuntu it didn't work.

OR 

Can you please suggest me a way to upgrade ILO3 DL360 Gen7 using any utility or other way?

Thanks!

**Comment by starnikser** [comment]
You can open web ui and update firmware from there.

**Comment by shaikk-arch** [comment]
Thank you for your response @starnikser 

I want to keep it in my python script ?

**Comment by AlexanderAmelkin** [comment]
Sorry, this must be asked/discussed on HP support forums as `ipmitool` has nothing to do with it.
