### ISSUE TITLE
ipmitool chassis bootdev floppy options=efiboot,persistent not work

### ISSUE THREAD

**Issue by Silentman7979** [ipmitool/ipmitool#258]

**Comment by Silentman7979** [comment]
Hi everyone,

The command ipmitool chassis bootdev floppy does not work or is not supported. Anybody help me this issue. More information, I found out the information [https://www.supermicro.com/support/faqs/faq.cfm?faq=21361](url)

Thanks
mrwhite

**Comment by doublechiang** [comment]
Have you tried up-to-dated master branch code?
There is a fix recently. check  #163

**Comment by Silentman7979** [comment]
The ipmitool version "ipmitool version 1.8.18.211.g050f5da", which was built. So I will try against and share the result to you.

Thanks for your support.!

**Comment by Silentman7979** [comment]
Thanks for your information @doublechiang !
I set the boot-option at floppy device completely. So I will close this ticket!

This is the result when I use ipmitool get the boot option

```
bootparam get 5
Boot parameter version: 1
Boot parameter 5 is valid/unlocked
Boot parameter data: a03c000000
 Boot Flags :
   - Boot Flag Valid
   - Options apply to only next boot
   - BIOS EFI boot 
   - Boot Device Selector : Force Boot from Floppy/primary removable media
   - Console Redirection control : System Default
   - BIOS verbosity : Console redirection occurs per BIOS configuration setting (default)
   - BIOS Mux Control Override : BIOS uses recommended setting of the mux at the end of POST

```
