### ISSUE TITLE
Using Ipmitool as a library?

### ISSUE THREAD

**Issue by vvsteg** [ipmitool/ipmitool#27]
Is there an API that allows calling Ipmitool from other programs? 
Is it possible to use Ipmitool as a library? 
E.g. FreeIPMI provides this capability via the libipmimonitoring library.

**Comment by AlexanderAmelkin** [comment]
It's not possible and not advised as of now. The tool has been initially developed without that application in mind and has a real lot of places that will go wild in multi-threaded or otherwise reentrable environment.

I'm sad to say that I recommend using OpenIPMI instead if you need a library.

**Comment by vvsteg** [comment]
Ok. I see. Thank you.
