### ISSUE TITLE
Power Supply Sensor Event(07h) cannot be triggered.

### ISSUE THREAD

**Issue by JacksonWen0126** [ipmitool/ipmitool#280]
Unable to trigger Power Supply Inactive Event log due to ipmi_sel.h header didn't match the IPMI spec.  
![image](https://user-images.githubusercontent.com/49283813/113633122-06b52c80-9632-11eb-8b6f-c898ec3c85bd.png)  
![image](https://user-images.githubusercontent.com/49283813/113633202-2187a100-9632-11eb-90cd-d43a223da9a6.png)

**Comment by AlexanderAmelkin** [comment]
@JacksonWen0126, does #281 fix it for you?

**Comment by JacksonWen0126** [comment]
Yes, thank you.
