### ISSUE TITLE
Expanding "mc info" or "bmc info" number of characters for "Firmware Revision"

### ISSUE THREAD

**Issue by torehl** [ipmitool/ipmitool#323]
Minor reporting issue, but it has been annoying me for a while.

"mc info" or "-I open bmc info"  only reports 3 characters instead of full IPMI firmware version number. 

Easy fix?   

```
$ grep -r "Firmware Revision" *
ChangeLog:	* added fix for tracker ID 2849300 "Incorrect Firmware Revision"
lib/ipmi_fwum.c:		printf("Firmware Revision         : %u.%u%u",
lib/ipmi_fwum.c:		printf("Firmware Revision         : %u.%u%u",
lib/ipmi_fwum.c:		printf("Firmware Revision          : %u.%u%u SDR %u\n",
lib/ipmi_ime.c:      printf("Intel ME Firmware Revision : %x.%02x.%02x.%x%x%x.%x\n",
lib/ipmi_mc.c:	printf("Firmware Revision         : %u.%02x\n",       
```

```
root@n014:~# ipmitool -V
ipmitool version 1.8.18

root@n014:~# ipmitool mc info
Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 3.10               <<<<<<<----------   Version is 3.10.17
IPMI Version              : 2.0
Manufacturer ID           : 10876
Manufacturer Name         : Supermicro
Product ID                : 6996 (0x1b54)
Product Name              : Unknown (0x1B54)
Device Available          : yes
Provides Device SDRs      : no
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    IPMB Event Generator
    Chassis Device
Aux Firmware Rev Info     : 
    0x17
    0x01
    0x00
    0x00
```

**Comment by AlexanderAmelkin** [comment]
At a first glance it appears to me that you're probably confusing IPMI Firmware revision with Intel ME Firmware revision.
What `ipmitool mc info` reports is the response to IPMI `Get Device ID` command, please see IPMI 2.0 Specification.
The response only contains two components, the major and the minor revision:

![image](https://user-images.githubusercontent.com/4518124/143218828-c1985636-713d-4ef3-8265-f2615f8b8513.png)

To find out the Intel ME firmware revision, please consult your vendor (Supermicro) if they provide any OEM command to get that. Please note that ipmitool is NOT talking to Intel ME, it is talking to a BMC (which is not Intel ME).
