### ISSUE TITLE
ipmitool chassis restart_cause could not valid the new status

### ISSUE THREAD

**Issue by jiruiwu** [ipmitool/ipmitool#329]
The legacy ipmitool only support 10 types of restart cause listed below,
 +---+-----------------------------------------------+
 | 0 | unknown                                       |
 +---+-----------------------------------------------+
 | 1 | chassis power control command                 |
 +---+-----------------------------------------------+
 | 2 | reset via pushbutton                          |
 +---+-----------------------------------------------+
 | 3 | power-up via pushbutton                       |
 +---+-----------------------------------------------+
 | 4 | watchdog expired                              |
 +---+-----------------------------------------------+
 | 5 | OEM                                           |
 +---+-----------------------------------------------+
 | 6 | power-up due to always-restore power policy   |
 +---+-----------------------------------------------+
 | 7 | power-up due to restore-previous power policy |
 +---+-----------------------------------------------+
 | 8 | reset via PEF                                 |
 +---+-----------------------------------------------+
 | 9 | power-cycle via PEF                           |
 +---+-----------------------------------------------+
 
However, there are more new restart conditions recently, such as,
 +---+-----------------------------------------------+
 | a | SoftReset                                     |
 +---+-----------------------------------------------+
 | b | RTCWakeup                                     |
 +---+-----------------------------------------------+

**Comment by AlexanderAmelkin** [comment]
Please check if the commit above works for you
