### ISSUE TITLE
CPU power consumption

### ISSUE THREAD

**Issue by Marlonsmart** [ipmitool/ipmitool#339]
When I want to set the CPU power, ipmitool dcmi power set_limit <parameter> <value> ,What specific parameters does <parameter> <value> in this command refer to?

**Comment by doublechiang** [comment]
you can refer to ipmi_dcmi.c, function ipmi_dcmi_set_limit(...).
It sends Netfun Group Extenstion. 0x2c to BMC.

**Comment by Marlonsmart** [comment]
Ok, I'll try it first. Thank you very much.

**Comment by AlexanderAmelkin** [comment]
Please next time use Discussuons (https://github.com/ipmitool/ipmitool/discussions)
