### ISSUE TITLE
The 'lanplus' Interface Is Not Default Enabled

### ISSUE THREAD

**Issue by LuvLetter** [ipmitool/ipmitool#34]
```
ipmitool 1.8.18.62.g2ed677c

Interfaces
  lan     : yes
  lanplus : no
  open    : yes
  free    : no
  imb     : yes
  bmc     : no
  usb     : no
  lipmi   : no
  serial  : yes
  dummy   : no

Extra tools
  ipmievd   : yes
  ipmishell : no
```
I have checked the output from the `configure`, but there is no more info about the var which enable certain interface.

**Comment by AlexanderAmelkin** [comment]
I see you've figured it out yourself, but just for the sake of others who will search for the answer: `libssl-dev` package is required for `lanplus` interface.
