### ISSUE TITLE
Can't use ipmitool on CentOS7(VM)

### ISSUE THREAD

**Issue by no-trifling** [ipmitool/ipmitool#345]
Can I use impitool on a virtual machine?

I carried out the following commands:
> yum install ipmitool
> modprobe ipmi_msghandler
> modprobe ipmi_devintf

But when I execute `ipmitool -I open shell`.
It still returns `Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory`.

**Comment by AlexanderAmelkin** [comment]
@no-trifling if your virtual machine doesn't provide a virtual KCS device for a real KCS, then you can only use ipmitool over lan using the "-I lanplus" option. I'm sorry, I'm not aware of any VMs that virtualize KCS.

**Comment by no-trifling** [comment]
Thanks, I'll try.

**Comment by coklm** [comment]
Virtual machines need hypervisor implements IPMI，
These days, such a beast does exist for libvirt, called [VirtualBMC](https://github.com/openstack/virtualbmc).
