### ISSUE TITLE
Error in open session response message : invalid authentication algorithm

### ISSUE THREAD

**Issue by k82cn** [ipmitool/ipmitool#350]
I got the following error when check the status of BMC, does that because of version mismatch?

```
$ ipmitool -V
ipmitool version 1.8.18
```

```
$ ipmitool -I lanplus -H x.x.x.x -L ADMINISTRATOR -U root -R 1 -N 5 -P xxx mc info
Error in open session response message : invalid authentication algorithm

Error: Unable to establish IPMI v2 / RMCP+ session
```

**Comment by AlexanderAmelkin** [comment]
This is because your BMC has apparently dropped support for cipher suite 3 that is default in 1.8.18.
Try to use `-C 17` or just use the latest code from github where auto-negotiation of cipher suite has been fixed.
