### ISSUE TITLE
Not able to make ipmitool 1.8.18

### ISSUE THREAD

**Issue by tahirahmad1985** [ipmitool/ipmitool#36]
i am trying to compile ipmitool 1.8.18 on ubuntu 16.04 server edition, but facing some issues

./bootstrap         #executes ok
./configure         #works fine 

but i run make command then i receive this error

root@FWA-3260:~/ipmitool-1.8.18# make
make  all-recursive
make[1]: Entering directory '/root/ipmitool-1.8.18'
Making all in lib
make[2]: Entering directory '/root/ipmitool-1.8.18/lib'
depbase=`echo helper.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
@LIBTOOL@  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -g -O2 -Wall -Wextra -std=gnu99 -pedantic -Wformat -Wformat-nonliteral -MT helper.lo -MD -MP -MF $depbase.Tpo -c -o helper.lo helper.c &&\
mv -f $depbase.Tpo $depbase.Plo
/bin/bash: line 1: @LIBTOOL@: command not found
Makefile:494: recipe for target 'helper.lo' failed
make[2]: *** [helper.lo] Error 127
make[2]: Leaving directory '/root/ipmitool-1.8.18/lib'
Makefile:441: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/ipmitool-1.8.18'
Makefile:382: recipe for target 'all' failed
make: *** [all] Error 2
root@FWA-3260:~/ipmitool-1.8.18#

**Comment by AlexanderAmelkin** [comment]
This is not an ipmitool issue. Your build system setup is incomplete. Please install `libtool`.
