### ISSUE TITLE
After the kernel version was upgraded from 3.10 to 4.19, the speed of iPmitool Sensor was particularly slow

### ISSUE THREAD

**Issue by zhuzongzhen** [ipmitool/ipmitool#372]
![image](https://user-images.githubusercontent.com/21327212/194984299-51a1bf2a-110c-4e99-b4f2-c65208f44b23.png)

**Comment by AlexanderAmelkin** [comment]
@zhuzongzhen The logic dictates that if in a system with two components the behavior changed after one component remained intact and the other changed, the latter is the one to blame.

Why did you decide to open a ticket with ipmitool rather than kernel?
