### ISSUE TITLE
Dimm calculation is not proper in SEL logs for DELL OEM specific.

### ISSUE THREAD

**Issue by ravisaripalli** [ipmitool/ipmitool#41]
Problem : When get sel list command is issued on DELL 14G servers , the DIMM numbering is not shown properly. 
Root cause : While converting the SEL data to human readable format for OEM specific strings, the DIMM calculation is not proper in "get_dell_evt_desc"

**Comment by AlexanderAmelkin** [comment]
Any patch or pull request for this? I don't have a DELL 14G server to verify/debug this.

**Comment by AlexanderAmelkin** [comment]
An example of how exactly "the DIMM numbering is not shown properly" is needed. Please provide the actual and the expected outputs.

**Comment by ravisaripalli** [comment]
Closing the issue, Will re-post with all request data.
