### ISSUE TITLE
configure SEL to read sensor data every five minutes

### ISSUE THREAD

**Issue by mousumipaul** [ipmitool/ipmitool#43]
Hi I am new to ipmitool. I just want to know that is it possible to configure SEL to read sensor data on every five minutes and have a record for that.

**Comment by AlexanderAmelkin** [comment]
SELs don't read sensors. SELs are just event logs. The thing you can configure is PEFs. And according to IPMI spec you can only configure PEFs to take action (includtion creation of SEL entries) on pre-configured events like threshold crossing. Anyway, this has almost nothing to do with ipmitool. All functionality is described in [IPMI specification](https://www.intel.com/content/www/us/en/servers/ipmi/ipmi-intelligent-platform-mgt-interface-spec-2nd-gen-v2-0-spec-update.html) and is implemented by your BMC firmware. If you find anything crucial to your task that is in IPMI specificaiton but isn't supported by ipmitool, then please report.
