### ISSUE TITLE
warnings and errors(pointing to ipmi_strings) generated when running make

### ISSUE THREAD

**Issue by venka66** [ipmitool/ipmitool#44]
Observing a lot of warnings and an error(pointing to ipmi_strings) generated when running make.
Am I missing any configuration steps before trying to build the software?.

[root@localhost ipmitool-source]# make
make  all-recursive
make[1]: Entering directory `/root/venka/tools/ipmitool-source'
Making all in lib
make[2]: Entering directory `/root/venka/tools/ipmitool-source/lib'
depbase=`echo ipmi_strings.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool --silent  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -g -O2 -Wall -Wextra -std=gnu11 -pedantic -Wformat -Wformat-nonliteral -MT ipmi_strings.lo -MD -MP -MF $depbase.Tpo -c -o ipmi_strings.lo ipmi_strings.c &&\
mv -f $depbase.Tpo $depbase.Plo
In file included from ../include/ipmitool/ipmi_sensor.h:38:0,
                 from ipmi_strings.c:36:
../include/ipmitool/ipmi.h:75:3: warning: type of bit-field 'netfn' is a GCC extension [-Wpedantic]
   uint8_t netfn:6;
   ^
../include/ipmitool/ipmi.h:76:3: warning: type of bit-field 'lun' is a GCC extension [-Wpedantic]
   uint8_t lun:2;
   ^
In file included from ../include/ipmitool/ipmi_sdr.h:44:0,
                 from ../include/ipmitool/ipmi_sensor.h:39,
                 from ipmi_strings.c:36:
../include/ipmitool/ipmi_entity.h:45:2: warning: type of bit-field 'instance' is a GCC extension [-Wpedantic]
  uint8_t instance    : 7; /* instance number */
  ^
../include/ipmitool/ipmi_entity.h:46:2: warning: type of bit-field 'logical' is a GCC extension [-Wpedantic]
  uint8_t logical     : 1; /* physical/logical */
  ^
In file included from ../include/ipmitool/ipmi_sensor.h:39:0,
                 from ipmi_strings.c:36:
../include/ipmitool/ipmi_sdr.h:215:4: warning: type of bit-field 'assert_lnc_low' is a GCC extension [-Wpedantic]
    uint16_t assert_lnc_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:216:4: warning: type of bit-field 'assert_lnc_high' is a GCC extension [-Wpedantic]
    uint16_t assert_lnc_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:217:4: warning: type of bit-field 'assert_lcr_low' is a GCC extension [-Wpedantic]
    uint16_t assert_lcr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:218:4: warning: type of bit-field 'assert_lcr_high' is a GCC extension [-Wpedantic]
    uint16_t assert_lcr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:219:4: warning: type of bit-field 'assert_lnr_low' is a GCC extension [-Wpedantic]
    uint16_t assert_lnr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:220:4: warning: type of bit-field 'assert_lnr_high' is a GCC extension [-Wpedantic]
    uint16_t assert_lnr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:221:4: warning: type of bit-field 'assert_unc_low' is a GCC extension [-Wpedantic]
    uint16_t assert_unc_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:222:4: warning: type of bit-field 'assert_unc_high' is a GCC extension [-Wpedantic]
    uint16_t assert_unc_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:223:4: warning: type of bit-field 'assert_ucr_low' is a GCC extension [-Wpedantic]
    uint16_t assert_ucr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:224:4: warning: type of bit-field 'assert_ucr_high' is a GCC extension [-Wpedantic]
    uint16_t assert_ucr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:225:4: warning: type of bit-field 'assert_unr_low' is a GCC extension [-Wpedantic]
    uint16_t assert_unr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:226:4: warning: type of bit-field 'assert_unr_high' is a GCC extension [-Wpedantic]
    uint16_t assert_unr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:227:4: warning: type of bit-field 'status_lnc' is a GCC extension [-Wpedantic]
    uint16_t status_lnc:1;
    ^
../include/ipmitool/ipmi_sdr.h:228:4: warning: type of bit-field 'status_lcr' is a GCC extension [-Wpedantic]
    uint16_t status_lcr:1;
    ^
../include/ipmitool/ipmi_sdr.h:229:4: warning: type of bit-field 'status_lnr' is a GCC extension [-Wpedantic]
    uint16_t status_lnr:1;
    ^
../include/ipmitool/ipmi_sdr.h:230:4: warning: type of bit-field 'reserved' is a GCC extension [-Wpedantic]
    uint16_t reserved:1;
    ^
../include/ipmitool/ipmi_sdr.h:250:4: warning: type of bit-field 'deassert_lnc_low' is a GCC extension [-Wpedantic]
    uint16_t deassert_lnc_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:251:4: warning: type of bit-field 'deassert_lnc_high' is a GCC extension [-Wpedantic]
    uint16_t deassert_lnc_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:252:4: warning: type of bit-field 'deassert_lcr_low' is a GCC extension [-Wpedantic]
    uint16_t deassert_lcr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:253:4: warning: type of bit-field 'deassert_lcr_high' is a GCC extension [-Wpedantic]
    uint16_t deassert_lcr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:254:4: warning: type of bit-field 'deassert_lnr_low' is a GCC extension [-Wpedantic]
    uint16_t deassert_lnr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:255:4: warning: type of bit-field 'deassert_lnr_high' is a GCC extension [-Wpedantic]
    uint16_t deassert_lnr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:256:4: warning: type of bit-field 'deassert_unc_low' is a GCC extension [-Wpedantic]
    uint16_t deassert_unc_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:257:4: warning: type of bit-field 'deassert_unc_high' is a GCC extension [-Wpedantic]
    uint16_t deassert_unc_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:258:4: warning: type of bit-field 'deassert_ucr_low' is a GCC extension [-Wpedantic]
    uint16_t deassert_ucr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:259:4: warning: type of bit-field 'deassert_ucr_high' is a GCC extension [-Wpedantic]
    uint16_t deassert_ucr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:260:4: warning: type of bit-field 'deassert_unr_low' is a GCC extension [-Wpedantic]
    uint16_t deassert_unr_low:1;
    ^
../include/ipmitool/ipmi_sdr.h:261:4: warning: type of bit-field 'deassert_unr_high' is a GCC extension [-Wpedantic]
    uint16_t deassert_unr_high:1;
    ^
../include/ipmitool/ipmi_sdr.h:262:4: warning: type of bit-field 'status_unc' is a GCC extension [-Wpedantic]
    uint16_t status_unc:1;
    ^
../include/ipmitool/ipmi_sdr.h:263:4: warning: type of bit-field 'status_ucr' is a GCC extension [-Wpedantic]
    uint16_t status_ucr:1;
    ^
../include/ipmitool/ipmi_sdr.h:264:4: warning: type of bit-field 'status_unr' is a GCC extension [-Wpedantic]
    uint16_t status_unr:1;
    ^
../include/ipmitool/ipmi_sdr.h:265:4: warning: type of bit-field 'reserved_2' is a GCC extension [-Wpedantic]
    uint16_t reserved_2:1;
    ^
../include/ipmitool/ipmi_sdr.h:280:6: warning: type of bit-field 'readable' is a GCC extension [-Wpedantic]
      uint16_t readable:8;
      ^
../include/ipmitool/ipmi_sdr.h:281:6: warning: type of bit-field 'lnc' is a GCC extension [-Wpedantic]
      uint16_t lnc:1;
      ^
../include/ipmitool/ipmi_sdr.h:282:6: warning: type of bit-field 'lcr' is a GCC extension [-Wpedantic]
      uint16_t lcr:1;
      ^
../include/ipmitool/ipmi_sdr.h:283:6: warning: type of bit-field 'lnr' is a GCC extension [-Wpedantic]
      uint16_t lnr:1;
      ^
../include/ipmitool/ipmi_sdr.h:284:6: warning: type of bit-field 'unc' is a GCC extension [-Wpedantic]
      uint16_t unc:1;
      ^
../include/ipmitool/ipmi_sdr.h:285:6: warning: type of bit-field 'ucr' is a GCC extension [-Wpedantic]
      uint16_t ucr:1;
      ^
../include/ipmitool/ipmi_sdr.h:286:6: warning: type of bit-field 'unr' is a GCC extension [-Wpedantic]
      uint16_t unr:1;
      ^
../include/ipmitool/ipmi_sdr.h:287:6: warning: type of bit-field 'reserved' is a GCC extension [-Wpedantic]
      uint16_t reserved:2;
      ^
../include/ipmitool/ipmi_sdr.h:302:6: warning: type of bit-field 'lnc' is a GCC extension [-Wpedantic]
      uint16_t lnc:1;
      ^
../include/ipmitool/ipmi_sdr.h:303:6: warning: type of bit-field 'lcr' is a GCC extension [-Wpedantic]
      uint16_t lcr:1;
      ^
../include/ipmitool/ipmi_sdr.h:304:6: warning: type of bit-field 'lnr' is a GCC extension [-Wpedantic]
      uint16_t lnr:1;
      ^
../include/ipmitool/ipmi_sdr.h:305:6: warning: type of bit-field 'unc' is a GCC extension [-Wpedantic]
      uint16_t unc:1;
      ^
../include/ipmitool/ipmi_sdr.h:306:6: warning: type of bit-field 'ucr' is a GCC extension [-Wpedantic]
      uint16_t ucr:1;
      ^
../include/ipmitool/ipmi_sdr.h:307:6: warning: type of bit-field 'unr' is a GCC extension [-Wpedantic]
      uint16_t unr:1;
      ^
../include/ipmitool/ipmi_sdr.h:308:6: warning: type of bit-field 'reserved' is a GCC extension [-Wpedantic]
      uint16_t reserved:2;
      ^
../include/ipmitool/ipmi_sdr.h:309:6: warning: type of bit-field 'settable' is a GCC extension [-Wpedantic]
      uint16_t settable:8;
      ^
../include/ipmitool/ipmi_sdr.h:331:3: warning: type of bit-field 'lun' is a GCC extension [-Wpedantic]
   uint8_t lun:2; /* sensor owner lun */
   ^
../include/ipmitool/ipmi_sdr.h:332:3: warning: type of bit-field '__reserved' is a GCC extension [-Wpedantic]
   uint8_t __reserved:2;
   ^
../include/ipmitool/ipmi_sdr.h:333:3: warning: type of bit-field 'channel' is a GCC extension [-Wpedantic]
   uint8_t channel:4; /* channel number */
   ^
../include/ipmitool/ipmi_sdr.h:352:4: warning: type of bit-field 'sensor_scan' is a GCC extension [-Wpedantic]
    uint8_t sensor_scan:1;
    ^
../include/ipmitool/ipmi_sdr.h:353:4: warning: type of bit-field 'event_gen' is a GCC extension [-Wpedantic]
    uint8_t event_gen:1;
    ^
../include/ipmitool/ipmi_sdr.h:354:4: warning: type of bit-field 'type' is a GCC extension [-Wpedantic]
    uint8_t type:1;
    ^
../include/ipmitool/ipmi_sdr.h:355:4: warning: type of bit-field 'hysteresis' is a GCC extension [-Wpedantic]
    uint8_t hysteresis:1;
    ^
../include/ipmitool/ipmi_sdr.h:356:4: warning: type of bit-field 'thresholds' is a GCC extension [-Wpedantic]
    uint8_t thresholds:1;
    ^
../include/ipmitool/ipmi_sdr.h:357:4: warning: type of bit-field 'events' is a GCC extension [-Wpedantic]
    uint8_t events:1;
    ^
../include/ipmitool/ipmi_sdr.h:358:4: warning: type of bit-field 'scanning' is a GCC extension [-Wpedantic]
    uint8_t scanning:1;
    ^
../include/ipmitool/ipmi_sdr.h:359:4: warning: type of bit-field '__reserved' is a GCC extension [-Wpedantic]
    uint8_t __reserved:1;
    ^
../include/ipmitool/ipmi_sdr.h:370:4: warning: type of bit-field 'event_msg' is a GCC extension [-Wpedantic]
    uint8_t event_msg:2;
    ^
../include/ipmitool/ipmi_sdr.h:371:4: warning: type of bit-field 'threshold' is a GCC extension [-Wpedantic]
    uint8_t threshold:2;
    ^
../include/ipmitool/ipmi_sdr.h:372:4: warning: type of bit-field 'hysteresis' is a GCC extension [-Wpedantic]
    uint8_t hysteresis:2;
    ^
../include/ipmitool/ipmi_sdr.h:373:4: warning: type of bit-field 'rearm' is a GCC extension [-Wpedantic]
    uint8_t rearm:1;
    ^
../include/ipmitool/ipmi_sdr.h:374:4: warning: type of bit-field 'ignore' is a GCC extension [-Wpedantic]
    uint8_t ignore:1;
    ^
../include/ipmitool/ipmi_sdr.h:391:3: warning: type of bit-field 'pct' is a GCC extension [-Wpedantic]
   uint8_t pct:1;
   ^
../include/ipmitool/ipmi_sdr.h:392:3: warning: type of bit-field 'modifier' is a GCC extension [-Wpedantic]
   uint8_t modifier:2;
   ^
../include/ipmitool/ipmi_sdr.h:393:3: warning: type of bit-field 'rate' is a GCC extension [-Wpedantic]
   uint8_t rate:3;
   ^
../include/ipmitool/ipmi_sdr.h:394:3: warning: type of bit-field 'analog' is a GCC extension [-Wpedantic]
   uint8_t analog:2;
   ^
../include/ipmitool/ipmi_sdr.h:422:3: warning: type of bit-field 'count' is a GCC extension [-Wpedantic]
   uint8_t count:4;
   ^
../include/ipmitool/ipmi_sdr.h:423:3: warning: type of bit-field 'mod_type' is a GCC extension [-Wpedantic]
   uint8_t mod_type:2;
   ^
../include/ipmitool/ipmi_sdr.h:424:3: warning: type of bit-field '__reserved' is a GCC extension [-Wpedantic]
   uint8_t __reserved:2;
   ^
../include/ipmitool/ipmi_sdr.h:430:3: warning: type of bit-field 'mod_offset' is a GCC extension [-Wpedantic]
   uint8_t mod_offset:7;
   ^
../include/ipmitool/ipmi_sdr.h:431:3: warning: type of bit-field 'entity_inst' is a GCC extension [-Wpedantic]
   uint8_t entity_inst:1;
   ^
../include/ipmitool/ipmi_sdr.h:462:3: warning: type of bit-field 'lun' is a GCC extension [-Wpedantic]
   uint8_t lun:2; /* sensor owner lun */
   ^
../include/ipmitool/ipmi_sdr.h:463:3: warning: type of bit-field 'fru_owner' is a GCC extension [-Wpedantic]
   uint8_t fru_owner:2; /* fru device owner lun */
   ^
../include/ipmitool/ipmi_sdr.h:464:3: warning: type of bit-field 'channel' is a GCC extension [-Wpedantic]
   uint8_t channel:4; /* channel number */
   ^
../include/ipmitool/ipmi_sdr.h:480:3: warning: type of bit-field 'count' is a GCC extension [-Wpedantic]
   uint8_t count:4;
   ^
../include/ipmitool/ipmi_sdr.h:481:3: warning: type of bit-field 'mod_type' is a GCC extension [-Wpedantic]
   uint8_t mod_type:2;
   ^
../include/ipmitool/ipmi_sdr.h:482:3: warning: type of bit-field '__reserved' is a GCC extension [-Wpedantic]
   uint8_t __reserved:2;
   ^
../include/ipmitool/ipmi_sdr.h:488:3: warning: type of bit-field 'mod_offset' is a GCC extension [-Wpedantic]
   uint8_t mod_offset:7;
   ^
../include/ipmitool/ipmi_sdr.h:489:3: warning: type of bit-field 'entity_inst' is a GCC extension [-Wpedantic]
   uint8_t entity_inst:1;
   ^
../include/ipmitool/ipmi_sdr.h:534:3: warning: type of bit-field 'nominal_read' is a GCC extension [-Wpedantic]
   uint8_t nominal_read:1; /* nominal reading field specified */
   ^
../include/ipmitool/ipmi_sdr.h:535:3: warning: type of bit-field 'normal_max' is a GCC extension [-Wpedantic]
   uint8_t normal_max:1; /* normal max field specified */
   ^
../include/ipmitool/ipmi_sdr.h:536:3: warning: type of bit-field 'normal_min' is a GCC extension [-Wpedantic]
   uint8_t normal_min:1; /* normal min field specified */
   ^
../include/ipmitool/ipmi_sdr.h:537:3: warning: type of bit-field '__reserved' is a GCC extension [-Wpedantic]
   uint8_t __reserved:5;
   ^
../include/ipmitool/ipmi_sdr.h:581:2: warning: type of bit-field 'channel_num' is a GCC extension [-Wpedantic]
  uint8_t channel_num:4;
  ^
../include/ipmitool/ipmi_sdr.h:582:2: warning: type of bit-field '__reserved2' is a GCC extension [-Wpedantic]
  uint8_t __reserved2:4;
  ^
../include/ipmitool/ipmi_sdr.h:589:2: warning: type of bit-field 'global_init' is a GCC extension [-Wpedantic]
  uint8_t global_init:4;
  ^
../include/ipmitool/ipmi_sdr.h:590:2: warning: type of bit-field '__reserved3' is a GCC extension [-Wpedantic]
  uint8_t __reserved3:1;
  ^
../include/ipmitool/ipmi_sdr.h:591:2: warning: type of bit-field 'pwr_state_notif' is a GCC extension [-Wpedantic]
  uint8_t pwr_state_notif:3;
  ^
../include/ipmitool/ipmi_sdr.h:613:2: warning: type of bit-field 'bus' is a GCC extension [-Wpedantic]
  uint8_t bus:3;
  ^
../include/ipmitool/ipmi_sdr.h:614:2: warning: type of bit-field 'lun' is a GCC extension [-Wpedantic]
  uint8_t lun:2;
  ^
../include/ipmitool/ipmi_sdr.h:615:2: warning: type of bit-field '__reserved2' is a GCC extension [-Wpedantic]
  uint8_t __reserved2:2;
  ^
../include/ipmitool/ipmi_sdr.h:616:2: warning: type of bit-field 'logical' is a GCC extension [-Wpedantic]
  uint8_t logical:1;
  ^
../include/ipmitool/ipmi_sdr.h:622:2: warning: type of bit-field '__reserved3' is a GCC extension [-Wpedantic]
  uint8_t __reserved3:4;
  ^
../include/ipmitool/ipmi_sdr.h:623:2: warning: type of bit-field 'channel_num' is a GCC extension [-Wpedantic]
  uint8_t channel_num:4;
  ^
../include/ipmitool/ipmi_sdr.h:648:2: warning: type of bit-field 'bus' is a GCC extension [-Wpedantic]
  uint8_t bus:3;
  ^
../include/ipmitool/ipmi_sdr.h:649:2: warning: type of bit-field 'lun' is a GCC extension [-Wpedantic]
  uint8_t lun:2;
  ^
../include/ipmitool/ipmi_sdr.h:650:2: warning: type of bit-field 'channel_num' is a GCC extension [-Wpedantic]
  uint8_t channel_num:3;
  ^
../include/ipmitool/ipmi_sdr.h:656:2: warning: type of bit-field '__reserved1' is a GCC extension [-Wpedantic]
  uint8_t __reserved1:5;
  ^
../include/ipmitool/ipmi_sdr.h:657:2: warning: type of bit-field 'addr_span' is a GCC extension [-Wpedantic]
  uint8_t addr_span:3;
  ^
../include/ipmitool/ipmi_sdr.h:683:3: warning: type of bit-field '__reserved' is a GCC extension [-Wpedantic]
   uint8_t __reserved:5;
   ^
../include/ipmitool/ipmi_sdr.h:684:3: warning: type of bit-field 'isaccessable' is a GCC extension [-Wpedantic]
   uint8_t isaccessable:1;
   ^
../include/ipmitool/ipmi_sdr.h:685:3: warning: type of bit-field 'islinked' is a GCC extension [-Wpedantic]
   uint8_t islinked:1;
   ^
../include/ipmitool/ipmi_sdr.h:686:3: warning: type of bit-field 'isrange' is a GCC extension [-Wpedantic]
   uint8_t isrange:1;
   ^
../include/ipmitool/ipmi_sdr.h:730:2: warning: type of bit-field 'get_sdr_repository_allo_info_supported' is a GCC extension [-Wpedantic]
  uint8_t get_sdr_repository_allo_info_supported:1;
  ^
../include/ipmitool/ipmi_sdr.h:731:2: warning: type of bit-field 'reserve_sdr_repository_supported' is a GCC extension [-Wpedantic]
  uint8_t reserve_sdr_repository_supported:1;
  ^
../include/ipmitool/ipmi_sdr.h:732:2: warning: type of bit-field 'partial_add_sdr_supported' is a GCC extension [-Wpedantic]
  uint8_t partial_add_sdr_supported:1;
  ^
../include/ipmitool/ipmi_sdr.h:733:2: warning: type of bit-field 'delete_sdr_supported' is a GCC extension [-Wpedantic]
  uint8_t delete_sdr_supported:1;
  ^
../include/ipmitool/ipmi_sdr.h:734:2: warning: type of bit-field '__reserved1' is a GCC extension [-Wpedantic]
  uint8_t __reserved1:1;
  ^
../include/ipmitool/ipmi_sdr.h:735:2: warning: type of bit-field 'modal_update_support' is a GCC extension [-Wpedantic]
  uint8_t modal_update_support:2;
  ^
../include/ipmitool/ipmi_sdr.h:736:2: warning: type of bit-field 'overflow_flag' is a GCC extension [-Wpedantic]
  uint8_t overflow_flag:1;
  ^
In file included from ipmi_strings.c:37:0:
../include/ipmitool/ipmi_sel.h:83:2: warning: type of bit-field 'event_type' is a GCC extension [-Wpedantic]
  uint8_t event_type : 7;
  ^
../include/ipmitool/ipmi_sel.h:84:2: warning: type of bit-field 'event_dir' is a GCC extension [-Wpedantic]
  uint8_t event_dir  : 1;
  ^
In file included from ipmi_strings.c:46:0:
ipmi_pen_list.inc.c:1:3: error: expected expression before ',' token
 { , "" },
   ^
ipmi_pen_list.inc.c:1:3: warning: missing initializer for field 'val' of 'const struct valstr' [-Wmissing-field-initializers]
In file included from ../include/ipmitool/ipmi_strings.h:36:0,
                 from ipmi_strings.c:34:
../include/ipmitool/helper.h:66:11: note: 'val' declared here
  uint32_t val;
           ^
make[2]: *** [ipmi_strings.lo] Error 1
make[2]: Leaving directory `/root/venka/tools/ipmitool-source/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/venka/tools/ipmitool-source'
make: *** [all] Error 2

**Comment by AlexanderAmelkin** [comment]
Have you done `./bootstrap` and `./configure` before running `make` ?
What OS and architecture are you using?
