### ISSUE TITLE
[SOL] ipmi_sol.c session timeout hard-coded

### ISSUE THREAD

**Issue by GuoYiLee** [ipmitool/ipmitool#87]
function ipomi_sol_activate() in ipmi_sol.c hard-code the sol session timeout to be 1 second:
intf->session->timeout = 1;
it should be configurable through "-N" option.

**Comment by AlexanderAmelkin** [comment]
It appears like this is a left-over from commit c9bd5b5b that added the `-N` option but forgot to clean that assignment in `ipmi_sol.c`. I will remove it.

**Comment by AlexanderAmelkin** [comment]
There is currently no release plan and so far I don't feel like the code is good enough or have accumulated enough changes for the next release.
